### ISSUE TITLE
第161页 中间那段代码 mapStateTopProps 多写了个 p

### ISSUE THREAD

**Issue by amydnt** [mocheng/react-and-redux#10]
上边一行都还是 mapStateToProps 

![img_20170524_021202r](https://cloud.githubusercontent.com/assets/481622/26369423/3327cf6c-4027-11e7-8a94-bcaada0ebe65.jpg)

对应的代码文件  chapter-07/weather_redux/src/weather/views.js  里也多了个 p

**Comment by mocheng** [comment]
谢谢，下一次印刷会更正。

**Comment by mocheng** [comment]
谢谢，2017.6重印版更正了这个错误。
