### ISSUE TITLE
17页关于高内聚的理解

### ISSUE THREAD

**Issue by huijian3139** [mocheng/react-and-redux#18]
我觉得高内聚是指模块内部高度聚合，功能专一，“把逻辑相关的内容放在一个组件中”并不准确。
该段的例子，把一个功能的css，js放在多个文件中，并没有违背高内聚，因为对于单个css来说，它是功能单一的。
个人浅见

**Comment by mocheng** [comment]
如书中所说，服务于某个模块的css，逻辑上是属于这个模块的，代表内容的HTML、代表行为的JS、代表样式的CSS，逻辑上就是为了这个模块而服务，把它们割裂开，纯粹是技术的分割，而不是功能的分割，其实它们就该放在一起。
