### ISSUE TITLE
2.3.2 的一些疑问

### ISSUE THREAD

**Issue by alekoshen712** [mocheng/react-and-redux#21]
关于componentWillReceiveProps函数的

p31的下半段
当点击强制刷新按钮后(即调用forceUpdate方法的按钮)
控制台输出了

enter ControlPanel render
enter componentWillReceiveProps First
enter render First
enter componentWillReceiveProps Second
enter render Second
enter componentWillReceiveProps Third
enter render Third

实际上只输出了
enter ControlPanel render
enter componentWillReceiveProps First
enter componentWillReceiveProps Second
enter componentWillReceiveProps Third

照我理解是因为组件state和props并没有发生改变,所以不会触发render函数

请问这是react版本的问题还是笔误?

感谢您的查看!书写的很好!非常感谢

**Comment by chris421** [comment]
你把 shouldComponentUpdate() 拿掉应该就跟书上显示的一样了.

原因是作者放在 github 上 chapter-02 的代码是完成章节后的版本.

在 p33 第三段: '让我们尝试给 Counter 组件增加一个 shouldComponentUpdate 函数',
可见在 p31 的版本 shouldComponentUpdate 应该还是预设的 return true.

**Comment by alekoshen712** [comment]
@chris421 
thanks.
果然如此.谢谢解答
