### ISSUE TITLE
chapter-03/redux_with_context中 Summary.js 中有错误

### ISSUE THREAD

**Issue by mansters** [mocheng/react-and-redux#23]
Summary 在这里应该为一个无状态组件了, 不存在 state , 应为 props
[在 `Summary.js` 中第5行](https://github.com/mocheng/react-and-redux/blob/master/chapter-03/redux_with_context/src/views/Summary.js#L5)
```javascript
const sum = this.state.sum;
```
应改为
```javascript
const sum = this.props.sum;
```

**Comment by chris421** [comment]
补充一下, [在 SummaryContainer 组件的 render() 没用到 Summary组件](https://github.com/mocheng/react-and-redux/blob/master/chapter-03/redux_with_context/src/views/Summary.js#L54)

```
  render() {
    const sum = this.state.sum;
    return (
      <div>Total Count: {sum}</div>
    );
  }
```
应改为
```
  render() {
    return (      
      <Summary sum={this.state.sum}></Summary>                                          
    );
  }
```
