### ISSUE TITLE
chapter-04/todo里的constructor是否没有必要传入context了？

### ISSUE THREAD

**Issue by iloveyo123u1** [mocheng/react-and-redux#28]
你好，刚购买了你的书籍，我是个新手， 

根据目前的理解，
感觉chapter-04/todo里的constructor 只要传入props即可， 
因为 已经用上了redux，
用Provider把store传递给了组件， 那么这里的context是否就可以删除了？

看到代码多出了个context有点懵，因为感觉好像并没有用到

https://github.com/mocheng/react-and-redux/blob/master/chapter-04/todo/src/todos/views/addTodo.js#L8

**Comment by mocheng** [comment]
事实上如果不用context就可以不传递context，但是传递context是一个好习惯，谁知道将来是不是会用上context呢。

当然，一个更简洁的写法是这样。
```
constructor() {
  super(...arguments);
}
```
