### ISSUE TITLE
如何运行例子？ 

### ISSUE THREAD

**Issue by oldbig** [mocheng/react-and-redux#33]
我购买了电子版的纸版的，是个好读者吧:)
我发现这些例子在我的机器上都无法运行，比如进入任意一个例子目录下，以react-and-redux\chapter-03\react-redux为例，运行: npm start 后会出现如下错误：
`Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\dev\react\react-and-redux\chapter-03\redux_smart_dumb\scripts\start.js:7:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\dev\\tools\\nodejs\\node.exe" "C:\\dev\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! demo@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the demo@0.1.0 start script 'node scripts/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls demo
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\react\react-and-redux\chapter-03\redux_smart_dumb\npm-debug.log

C:\dev\react\react-and-redux\chapter-03\redux_smart_dumb>`

然后我运行： npm install -g dotenv
再运行： npm start
错误还是和开始时相同，我启动的方式不对吗？请给我一点提示吧， 谢谢了！

**Comment by atomextranova** [comment]
根目录下直接运行npm install（和package.json同目录下），然后npm start

**Comment by mocheng** [comment]
刚刚我删掉node_modules重新npm install，是能够工作的，不过我只有Mac环境。 

这个dotenv不是代码中直接依赖的库，应该在` ./node_modules/dotenv ` 这个位置，请试一试`npm install dotenv` 看能不能成功安装。

**Comment by oldbig** [comment]
可以正确运行了， 删掉node_modules, 重新npm install & npm start 就可以了。
谢谢老大。
