### ISSUE TITLE
关于164页fetch的中止问题

### ISSUE THREAD

**Issue by Wang-007** [mocheng/react-and-redux#38]
全局变量nextSeqId=0,局部变量seqId = ++nextSeqId;
第一次点击之后两个都为1，这时候走dispatch(),第二次点击的时候nextSeqId被赋值2，seqId也是2啊，即使在数据没有返回之前点击，这种写法也应该还是相等的，我不明白怎么就能不相等中止异步了？望解惑，谢谢

**Comment by mocheng** [comment]
fetch返回的是Promise，Promise是不能被中止的，只是当nextSeqId和seqId不同的时候，对于fetch的结果不做任何动作而已。
