### ISSUE TITLE
示例代码有误

### ISSUE THREAD

**Issue by wx1993** [mocheng/react-and-redux#43]
第二章 设计高质量的 React 组件 P27

示例代码：
Sample.defaultProps = {
   return { sampleProp: 0 }
}

defaultProps 中应该为键值对，所以 return 应该去掉，正确格式：
Sample.defaultProps = {
   sampleProp: 0
}

谢谢。

**Comment by mocheng** [comment]
在2017.6重印版中更正了这个问题。
