### ISSUE TITLE
P102页，关于redux-immutable-state-invariant部分的代码

### ISSUE THREAD

**Issue by kulley** [mocheng/react-and-redux#45]
具体仓库地址：[这里](https://github.com/mocheng/react-and-redux/blob/master/chapter-04/todo/src/Store.js) 第 18 行：
```
middlewares.push(require('redux-immutable-state-invariant')());
```
报错，指出 `require("redux-immutable-state-invariant") is not a function`。

查了这部分[文档](https://github.com/leoasis/redux-immutable-state-invariant#readme)，发现文档用法是
```
middlewares.push(require('redux-immutable-state-invariant').default());
```

不知是版本更新还是一处错误，更改后一切能正常运行。

**Comment by mocheng** [comment]
版本更新的问题，你可以开个PR来更新这个repo的代码。
