### ISSUE TITLE
关于同构分片浏览器端用match的疑惑

### ISSUE THREAD

**Issue by woleicom** [mocheng/react-and-redux#48]
请教作者一个问题（不算是issues，但是除了提issues，不知道还有什么联系方式了）：关于第12章 同构说的：
     如果应用没有使用代码分片，浏览器端的路由部分就无需任何改变，不过在我们的
例子中已经应用了代码分片，所以应用了服务器端渲染之后，浏览器端渲染也要做对应
修改，使用match函数来完成匹配，否则，服务器端和浏览器中产生的HTML会不一
致，这种不一致不是脱水数据问题导致，而是产生两端的代码不一致导致的。
这里我实在想不通，为什么不一致会导致html的不同，store数据一样，模版相同为什么要用match的方式？方便给解答下吗？
谢谢！

**Comment by mocheng** [comment]
参照这个 https://github.com/ReactTraining/react-router/blob/v3/docs/guides/ServerRendering.md#async-routes
你可以尝试把代码改成不使用match，我所描述的问题就一下子暴露出来了。

以后有问题可以在知乎上直接问： https://www.zhihu.com/people/morgancheng/activities
