### ISSUE TITLE
在这种情况,该依赖prevState来更新state吗?

### ISSUE THREAD

**Issue by Yeung2017** [mocheng/react-and-redux#50]
譬如在react-and-redux/chapter-02/controlpanel/src/Counter.js里
第43行至第45行
`  onClickIncrementButton() {
    this.setState({count: this.state.count + 1});
  }`
是否应该这样写
`onClickIncrementButton() {
        this.setState(prevState => ({
            count: ++prevState.count
        }));
    }`
因为根据[状态更新可能是异步](https://react.bootcss.com/react/docs/state-and-lifecycle.html)
这一节的说法,在这种情况下使用prevState更好
所以此时该依赖prevState来更新state吗,还是直接如源码一样不使用prevState也可以?

**Comment by mocheng** [comment]
书中用的setState都是接受对象作为参数，但是setState接受函数的方式更好，我的专栏有后续讨论 https://zhuanlan.zhihu.com/p/25954470
