### ISSUE TITLE
在使用typescript时，代码分片的require.ensure报错

### ISSUE THREAD

**Issue by ofzo** [mocheng/react-and-redux#60]
`error TS2339: Property 'ensure' does not exist on type 'NodeRequire'.`

请问应该如何解决

另外，书中提到的关于 import（）函数，我没有找到相关的资料，请问哪里可以找到

**Comment by mocheng** [comment]
这本书的代码没有任何使用TypeScript的部分。

import函数用搜索引擎一搜一大把，比如这个 http://2ality.com/2017/01/import-operator.html
