### ISSUE TITLE
2.3.1章节中，生命周期中this的指定的解释，感觉有问题

### ISSUE THREAD

**Issue by posuihushui** [mocheng/react-and-redux#63]
`在es6语法下`，类的每个成员函数在执行的this并不是和类实例自动绑定的。。。已经后面的对Bind的解释也不太对。

**Comment by chocolatl** [comment]
绑定的意思是无法修改上下文环境：

`(function(){console.log(this.name)}).bind({name: 'foo'}).call({name: 'bar'})`

上面的代码企图通过`call`修改上下文环境，但是失败了。在控制台依然会输出"foo"

**Comment by mocheng** [comment]
es6的class里一个函数foo，直接调用this.foo()当然在foo中this还是这个instance，但是把this.foo作为参数传递出去，或者赋值给一个变量，再把这个参数或者变量当做函数来执行，就失去了this。
