### ISSUE TITLE
关于react-redux桥接已有第三方组件的疑问

### ISSUE THREAD

**Issue by ylyxf** [mocheng/react-and-redux#66]
第72页第一行代码，使用connect连接了一个傻瓜组件。如果是我们自己开发的组件，那么我们会尽量写成傻瓜式的，但是像Ant Design这种的组件库，它不会假设有人把它当傻瓜组件，所以它内部应该也是有state的吧？如果使用react-redux的方式开发，connect(mstp,sdtp)(antd component)，是不是实际上内存中也有两份数据，一份是全局store保存的，一份是antd component内部保存的？

**Comment by mocheng** [comment]
组件之间的组合，包括react-redux，都不是修改原有组件，而是产生一个新的组件，里面组件的行为和外面也没有关系，对外面来说就是一个组件而已，有没有state无所谓。
