### ISSUE TITLE
Unexpected end of JSON input while parsing near '...{},"dist":{"shasum":"'

### ISSUE THREAD

**Issue by yxwandroid** [mocheng/react-and-redux#68]
我下载项目运行 npm install 的时候出现这个错误 
请问是什么原因导致的
这是错误信息
<img width="1223" alt="errojson" src="https://user-images.githubusercontent.com/9635493/32145510-e6fb328a-bc97-11e7-976c-f13c367a233f.png">
这是 log 文件    
[2017-10-29T15_46_29_585Z-debug.log](https://github.com/mocheng/react-and-redux/files/1425266/2017-10-29T15_46_29_585Z-debug.log)

谢谢

**Comment by mocheng** [comment]
看起来是`package.json`文件并不是合法的JSON格式。

**Comment by Jeff-Tian** [comment]
> 我下载项目运行 npm install 的时候出现这个错误
> 请问是什么原因导致的
> 这是错误信息
> <img alt="errojson" width="1223" src="https://user-images.githubusercontent.com/9635493/32145510-e6fb328a-bc97-11e7-976c-f13c367a233f.png">
> 这是 log 文件
> [2017-10-29T15_46_29_585Z-debug.log](https://github.com/mocheng/react-and-redux/files/1425266/2017-10-29T15_46_29_585Z-debug.log)
> 
> 谢谢

我 `npm cache clean --force` 后好了，参见：https://github.com/npm/npm/issues/19072#issuecomment-345555468
