### ISSUE TITLE
P25 2.3.1 装载过程的疑问

### ISSUE THREAD

**Issue by chocolatl** [mocheng/react-and-redux#70]
2.3.1 装载过程
- `constructor`
- `getInitialState`
- `getDefaultProps`

为什么`getInitialState`在`getDefaultProps`之前被调用，初始化组件的State不是需要依赖于Prop的默认值吗？

**Comment by mocheng** [comment]
这是一个错误，实际上getDefaultProps会在getInitialState之前被调用。
