### ISSUE TITLE
155页 讲thunk的时候, 注释里的结果有误

### ISSUE THREAD

**Issue by qin-zhuopu** [mocheng/react-and-redux#8]
我觉得不应该是(3+4)*5, 而是(3+4)+5=12
![img_8502](https://cloud.githubusercontent.com/assets/2142960/26271307/b917b518-3d36-11e7-9e8c-0d86dcd792c9.JPG)

**Comment by mocheng** [comment]
这是我笔误了，下一版会更正。

**Comment by mocheng** [comment]
2017.6重印版更正了这个错误。
